<?php

namespace alps\sharepreviews\controllers;

use alps\Module;
use alps\sharepreviews\models\ColorLayer;
use alps\sharepreviews\models\GradientLayer;
use alps\sharepreviews\models\Image;
use alps\sharepreviews\models\ImageLayer;
use alps\sharepreviews\models\LineLayer;
use alps\sharepreviews\models\TextLayer;
use alps\sharepreviews\SharePreviews;
use craft\elements\Entry;
use alps\sharepreviews\Config;
use alps\sharepreviews\services\FileHandler;
use alps\sharepreviews\services\FontFetcher;
use alps\sharepreviews\Plugin;
use alps\sharepreviews\services\Renderer;
use alps\youtube\Client;
use Craft;
use craft\web\Controller;
use League\OAuth2\Client\Provider\Google;
use yii\web\HttpException;

class PreviewController extends Controller
{
//    public $allowAnonymous = [
//        'actionIndex'
//    ];

    public $allowAnonymous = true;

    public function actionIndex(string $data)
    {
        $plugin = SharePreviews::getInstance();

        $image = Image::fromEncodedDiff($data);

        $settings = $plugin->getSettings();

        $image = $image->render();

        if ($settings->disableImageCache !== true) {
            $plugin->fileHandler->saveImage($image, $data);
        }

        $image->show('png', [
            'png_compression_level' => Renderer::PNG_COMPRESSION_LEVEL,
        ]);

        return;

        $plugin = SharePreviews::getInstance();

        $entry = Entry::find()->one();
        $imageFactory = $plugin->imageDiffer;
        $templates = $plugin->templates;

        $image = $templates->getDefaultTemplate()->setEntry($entry);

        dd($image->getUrl());

        $diff = $imageFactory->getDiff($imageFactory->getTemplate(), $image);

        $image = $imageFactory->createFromDiff($diff);

        // /preview/1234/90i3030ii0.png

        $encoded = $imageFactory->encodeDiff($diff);
        $decoded = $imageFactory->decodeDiff($encoded);
//        $zipped = gzdeflate($encoded, 9);
        dd(
            $image->toArray(), $diff, json_encode($diff), $encoded, $decoded,
            strlen($encoded),
        );

        $image->render()->show('png', [
            'png_compression_level' => Renderer::PNG_COMPRESSION_LEVEL,
        ]);

        return;
        $config = new Config;
        $renderer = $plugin->renderer;
        $fileHandler = $plugin->fileHandler;

        $this->ensureFontIsCached($fileHandler);

        $config->applyEncodedData($data);

        $image = $renderer
            ->withConfig($config)
            ->render();

        $settings = $plugin->getSettings();

        if ($settings->disableImageCache !== true) {
            $fileHandler->saveImage($image, $data);
        }

        $image->show('png', [
            'png_compression_level' => Renderer::PNG_COMPRESSION_LEVEL,
        ]);
    }

    private function ensureFontIsCached(FileHandler $fileHandler): self
    {
        if ($fileHandler->fontExists('Apercu Pro', 600)) {
            return $this;
        }

        $contents = file_get_contents(__DIR__ . '/../fonts/ApercuPro-Bold.ttf');

        $fileHandler->saveFont('Apercu Pro', 600, $contents);

        return $this;
    }

    public function actionDraft()
    {
        $id = $this->request->getRequiredParam('id');

        $entry = Entry::find()->draftId($id)->one();

        if (!$entry) {
            throw new HttpException(404, 'Draft not found');
        }

        $plugin = SharePreviews::getInstance();

        $imagesService = $plugin->images;

        if ($imagesService->autoGeneratedPreviewImagesEnabled($entry) === false) {
            $url = $imagesService->getShareImagePreviewUrl($entry);

            if (!$url) {
                throw new HttpException(404, 'Draft not found');
            }

            return $this->redirect($url);
        }

        $this->ensureFontIsCached($plugin->fileHandler);

        $config = $imagesService->createConfigFromEntry($entry);

        $image = (new Renderer)
            ->withConfig($config)
            ->render();

        $image->show('png', [
            'png_compression_level' => Renderer::PNG_COMPRESSION_LEVEL,
        ]);
    }
}
